In [3]:
# Import the required libraries
import numpy as np
import rasterio

input_file = 'Data/Lighting/Zambia_set_lightscore_sy_2019.tif'
output_file = 'Data/Lighting/Zambia_set_lightscore_sy_2019_modified.tif'

In [4]:
# Open the raster file as a numpy array
with rasterio.open(input_file) as src:
    raster = src.read()

    # Replace all Nan values by 0
    raster[raster == src.nodata] = 0

    # Save the modified raster as a new file
    with rasterio.open(output_file, "w", **src.profile) as dst:
        dst.write(raster)

print(raster)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
